// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddDetectedSession(arg1:models.LoginSession):Promise<void>;

export function CheckAndRenewLoginToken():Promise<boolean>;

export function CheckIfSessionIsNew(arg1:string):Promise<boolean>;

export function DetectNewLoginSession():Promise<models.LoginSession>;

export function GetCurrentLoginSession():Promise<models.LoginSession>;

export function MoveAsideActiveSession():Promise<void>;
