// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDetectedSession(arg1) {
  return window['go']['services']['AuthService']['AddDetectedSession'](arg1);
}

export function CheckAndRenewLoginToken() {
  return window['go']['services']['AuthService']['CheckAndRenewLoginToken']();
}

export function CheckIfSessionIsNew(arg1) {
  return window['go']['services']['AuthService']['CheckIfSessionIsNew'](arg1);
}

export function DetectNewLoginSession() {
  return window['go']['services']['AuthService']['DetectNewLoginSession']();
}

export function GetCurrentLoginSession() {
  return window['go']['services']['AuthService']['GetCurrentLoginSession']();
}

export function MoveAsideActiveSession() {
  return window['go']['services']['AuthService']['MoveAsideActiveSession']();
}
