// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectAndSaveAvatar(arg1) {
  return window['go']['services']['AvatarService']['SelectAndSaveAvatar'](arg1);
}

export function Startup(arg1) {
  return window['go']['services']['AvatarService']['Startup'](arg1);
}
