// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAvatarFile(arg1) {
  return window['go']['services']['AvatarService']['DeleteAvatarFile'](arg1);
}

export function GetAvailableAvatars() {
  return window['go']['services']['AvatarService']['GetAvailableAvatars']();
}

export function RemoveAvatar(arg1) {
  return window['go']['services']['AvatarService']['RemoveAvatar'](arg1);
}

export function SelectAndSaveAvatar(arg1) {
  return window['go']['services']['AvatarService']['SelectAndSaveAvatar'](arg1);
}

export function SetAvatar(arg1, arg2) {
  return window['go']['services']['AvatarService']['SetAvatar'](arg1, arg2);
}
