// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAvailableAvatars():Promise<Array<string>>;

export function RemoveAvatar(arg1:string):Promise<void>;

export function SelectAndSaveAvatar(arg1:string):Promise<string>;

export function SetAvatar(arg1:string,arg2:string):Promise<void>;
