// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiagnostics() {
  return window['go']['services']['DiagnosticService']['GetDiagnostics']();
}

export function SetLastError(arg1) {
  return window['go']['services']['DiagnosticService']['SetLastError'](arg1);
}
