// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['services']['IgnoreListStore']['Add'](arg1);
}

export function IsIgnored(arg1) {
  return window['go']['services']['IgnoreListStore']['IsIgnored'](arg1);
}

export function Load() {
  return window['go']['services']['IgnoreListStore']['Load']();
}

export function Save(arg1) {
  return window['go']['services']['IgnoreListStore']['Save'](arg1);
}

export function Unignore(arg1) {
  return window['go']['services']['IgnoreListStore']['Unignore'](arg1);
}
