// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1:string):Promise<void>;

export function IsIgnored(arg1:string):Promise<boolean>;

export function Load():Promise<Array<string>>;

export function Save(arg1:Array<string>):Promise<void>;

export function Unignore(arg1:string):Promise<void>;
