// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsernameForUserID(arg1) {
  return window['go']['services']['LogReaderService']['GetUsernameForUserID'](arg1);
}

export function SyncUsernames(arg1) {
  return window['go']['services']['LogReaderService']['SyncUsernames'](arg1);
}
