// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetUsernameForUserID(arg1:string):Promise<string>;

export function SyncUsernames(arg1:boolean):Promise<boolean>;
