// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteSession(arg1:string):Promise<void>;

export function GetAvatarDir():Promise<string>;

export function LoadSessions():Promise<Array<models.LoginSession>>;

export function SaveSessions(arg1:Array<models.LoginSession>):Promise<void>;

export function UpdateAlias(arg1:string,arg2:string):Promise<void>;

export function UpdateAvatar(arg1:string,arg2:string):Promise<void>;

export function UpdateAvatarColor(arg1:string,arg2:string):Promise<void>;
