// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSession(arg1) {
  return window['go']['services']['SessionStore']['DeleteSession'](arg1);
}

export function GetAvatarDir() {
  return window['go']['services']['SessionStore']['GetAvatarDir']();
}

export function LoadSessions() {
  return window['go']['services']['SessionStore']['LoadSessions']();
}

export function SaveSessions(arg1) {
  return window['go']['services']['SessionStore']['SaveSessions'](arg1);
}

export function UpdateAlias(arg1, arg2) {
  return window['go']['services']['SessionStore']['UpdateAlias'](arg1, arg2);
}

export function UpdateAvatar(arg1, arg2) {
  return window['go']['services']['SessionStore']['UpdateAvatar'](arg1, arg2);
}
