// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SwitchAccount(arg1) {
  return window['go']['services']['SwitchService']['SwitchAccount'](arg1);
}
