// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function GetDiagnostics():Promise<services.DiagnosticInfo>;

export function OpenDirectory(arg1:string):Promise<void>;
