// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDiagnostics() {
  return window['go']['services']['SystemService']['GetDiagnostics']();
}

export function OpenDirectory(arg1) {
  return window['go']['services']['SystemService']['OpenDirectory'](arg1);
}
